# fly.toml file generated for el-dorado-tanstack on 2025-11-14T21:39:57-07:00

app = "el-dorado-tanstack"


[build]
  dockerfile = "./Dockerfile.web"

[deploy]
  strategy = "rolling"

[env]
  PORT = "8080"

[[vm]]
  size = "shared-cpu-1x"
  memory = "256mb"
  count = 1

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
